- name: Install suckless dependencies
  block:
    - name: Install Suckless Deps debian
      when: ansible_os_family == 'Debian'
      become: true
      apt:
        name:
          - libxft-dev
          - libharfbuzz-dev
          - libxinerama-dev
          - libx11-xcb-dev
          - libxcb-res0-dev
            
    - name: Install Suckless Deps arch
      when: ansible_os_family == 'Archlinux'
      block:
        - name: Pacman Deps
          become: true
          pacman:
            name:
              - harfbuzz
              - libxinerama
              - libxcb
        - name: yay Deps
          shell: "yay --noconfirm -S {{ item }}"
          loop:
            - libxft-bgra-git

  tags:
    - install
    - suckless
    - st
    - dmenu
    - dwm
