- hosts: localhost

  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    GH_USER: "aldevv"

  pre_tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        state: present
  roles:
    - role: update # updates the package manager
      tags:
        - zsh
        - core

  tasks:
    - import_tasks: tasks/ssh.yml
      tags:
        - dotfiles
        - ssh

    - import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles

    - import_tasks: tasks/zsh.yml
      tags:
        - zsh
