- hosts: localhost
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    home: "{{ lookup('env', 'HOME') }}"
    dotfiles_repo_full: "git@github.com:aldevv/.dotfiles.git"
    dotfiles_repo: "https://github.com/aldevv/.dotfiles.git"
    work: "{{ lookup('env', 'WORK') or ansible_env.HOME ~ '/work' }}"
    projects: "{{ lookup('env', 'PROJECTS') or ansible_env.HOME ~ '/projects' }}"
    learn: "{{ lookup('env', 'LEARN') or ansible_env.HOME ~ '/learn' }}"
    code: "{{ lookup('env', 'CODE') or ansible_env.HOME ~ '/code' }}"
    programs: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}"
    builds: "{{ lookup('env', 'BUILDS') or ansible_env.HOME ~ '/.local/builds' }}"
    suckless_home: "{{ programs }}/suckless"

  roles:
    - role: auth
      tags:
        - install
        - auth

    - role: core
      tags:
        - install
        - core

  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml
  tasks:
    # always
    - import_tasks: tasks/folders.yml

    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/wiki.yml
    - import_tasks: tasks/sudoers.yml
    - import_tasks: tasks/hardware.yml

    - import_tasks: tasks/install/zsh.yml
    - import_tasks: tasks/install/fnm.yml
    - import_tasks: tasks/install/slack.yml

    - import_tasks: tasks/build/neovim.yml
    - import_tasks: tasks/build/suckless.yml
    - import_tasks: tasks/build/copyq.yml
    - import_tasks: tasks/build/dunst.yml
    - import_tasks: tasks/build/picom.yml
