- hosts: localhost

  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    # dotfiles_repo: "git@github.com:aldevv/dotfiles-chez.git"
    dotfiles_repo_full: "git@github.com:aldevv/.dotfiles.git"
    dotfiles_repo: "https://github.com/aldevv/.dotfiles.git"

  roles:
    - role: auth
      tags:
        - dotfiles-full # for auth
        - ssh

    - role: update
      tags:
        - zsh
        - core

    - role: core
      tags:
        - core

  tasks:

    - name: Check oh-my-zsh is installed
      stat:
        path: ~/.oh-my-zsh/
      register: p
      tags:
        - zsh
        - dotfiles
        - dotfiles-full

    - import_tasks: tasks/zsh.yml
      tags:
        - zsh
        - dotfiles
        - dotfiles-full
      when: p.stat.exists == False

    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - dotfiles-full
