- hosts: localhost

  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    dotfiles_repo: "git@github.com:aldevv/dotfiles-chez.git"

  roles:
    - role: auth # updates the package manager
      tags:
        - dotfiles-full # for auth
        - dotfiles
        - ssh

    - role: update # updates the package manager
      tags:
        - zsh
        - core

    - role: core # updates the package manager
      tags:
        - core

  tasks:
    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - dotfiles-full

    - import_tasks: tasks/zsh.yml
      tags:
        - zsh
