- hosts: localhost
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    home: "{{ lookup('env', 'HOME') }}"
    work: "{{ lookup('env', 'WORK') or ansible_env.HOME ~ '/work' }}"
    projects: "{{ lookup('env', 'PROJECTS') or ansible_env.HOME ~ '/projects' }}"
    learn: "{{ lookup('env', 'LEARN') or ansible_env.HOME ~ '/learn' }}"
    code: "{{ lookup('env', 'CODE') or ansible_env.HOME ~ '/code' }}"
    programs: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}"
    repos: "{{ lookup('env', 'REPOS') or ansible_env.HOME ~ '/repos' }}"
    builds: "{{ lookup('env', 'BUILDS') or ansible_env.HOME ~ '/.local/builds' }}"
    local: "{{ ansible_env.HOME ~ '/.local' }}"
    bin: "{{ ansible_env.HOME ~ '/.local/bin' }}"

  roles:
    - role: auth
      tags:
        - install
        - auth

    - role: core
      tags:
        - install
        - core

  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml
  tasks:
    # always
    # test if this always runs without explicitly calling it
    - import_tasks: tasks/folders.yml

    - import_tasks: tasks/work.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/dotfiles-work.yml
    - import_tasks: tasks/dotfiles-safe.yml
    - import_tasks: tasks/wiki.yml
    - import_tasks: tasks/sudoers.yml
    - import_tasks: tasks/hardware.yml

    - import_tasks: tasks/install/zsh.yml
    - import_tasks: tasks/install/fnm.yml
    - import_tasks: tasks/install/slack.yml
    - import_tasks: tasks/install/fd.yml
    - import_tasks: tasks/install/rg.yml
    - import_tasks: tasks/install/bob.yml
    - import_tasks: tasks/install/pomo.yml
    - import_tasks: tasks/install/doppler.yml

    # NOTE: these 2 are replaced by bob
    # - import_tasks: tasks/build/neovim.yml
    # - import_tasks: tasks/build/neovim-nightly.yml
    - import_tasks: tasks/build/suckless.yml
    - import_tasks: tasks/build/dunst.yml
    - import_tasks: tasks/build/picom.yml
    - import_tasks: tasks/build/autorandr.yml
    - import_tasks: tasks/build/copyq.yml
