- hosts: localhost
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    home: "{{ ansible_env.HOME }}"
    work: "{{ lookup('env', 'WORK') or ansible_env.HOME ~ '/work' }}"
    projects: "{{ lookup('env', 'PROJECTS') or home ~ '/projects' }}"
    learn: "{{ lookup('env', 'LEARN') or home ~ '/learn' }}"
    code: "{{ lookup('env', 'CODE') or home ~ '/code' }}"
    programs: "{{ lookup('env', 'PROGRAMS') or home ~ '/programs' }}"
    repos: "{{ lookup('env', 'REPOS') or home ~ '/repos' }}"
    builds: "{{ lookup('env', 'BUILDS') or home ~ '/.local/builds' }}"
    local: "{{ home }} /.local"
    bin: "{{home}}/.local/bin"
    dotfiles: "{{home}}/.dotfiles"

  roles:
    - role: auth
      tags:
        - install
        - auth

    - role: core
      tags:
        - install
        - core

  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml
  tasks:
    # always
    # test if this always runs without explicitly calling it
    - import_tasks: tasks/folders.yml

    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/work.yml

    - import_tasks: tasks/dotfiles.yml

    # TODO: fix it so that dotfiles-safe runs when fast running install, add new tag? fast install? divide the task into multiple blocks!!
    # - import_tasks: tasks/dotfiles-work.yml
    # - import_tasks: tasks/dotfiles-safe.yml
    - import_tasks: tasks/notes.yml
    - import_tasks: tasks/wiki.yml
    - import_tasks: tasks/sudoers.yml
      # TODO: this only works for intel computers!!
    - import_tasks: tasks/hardware/screen.yml
    - import_tasks: tasks/hardware/keyboard.yml

    - import_tasks: tasks/install/zsh.yml
    - import_tasks: tasks/install/fnm.yml
    - import_tasks: tasks/install/compressed/ripgrep_all.yml
    - import_tasks: tasks/install/compressed/bob.yml

    - import_tasks: tasks/install/slack.yml
    - import_tasks: tasks/install/fd.yml
    - import_tasks: tasks/install/rg.yml

    - import_tasks: tasks/install/binary/pomo.yml

    - import_tasks: tasks/install/script/doppler.yml

    - import_tasks: tasks/install/deb/obsidian.yml

    - import_tasks: tasks/install/git/forgit.yml

    - import_tasks: tasks/install/snap/zoom.yml
    - import_tasks: tasks/install/deb/docker.yml

    # NOTE: these 2 are replaced by bob
    # - import_tasks: tasks/build/neovim.yml
    # - import_tasks: tasks/build/neovim-nightly.yml
    - import_tasks: tasks/build/suckless.yml
    - import_tasks: tasks/build/xmonad.yml
    - import_tasks: tasks/build/dunst.yml
    - import_tasks: tasks/build/picom.yml
    - import_tasks: tasks/build/autorandr.yml
    - import_tasks: tasks/build/copyq.yml
