- hosts: localhost

  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    # dotfiles_repo: "git@github.com:aldevv/dotfiles-chez.git"
    dotfiles_repo_full: "git@github.com:aldevv/.dotfiles.git"
    dotfiles_repo: "https://github.com/aldevv/.dotfiles.git"
    nvim_nightly_home: "{{ ansible_env.HOME }}/.local/build/neovim"
    nvim_home: "{{ ansible_env.HOME }}/.local/programs/neovim"
    suckless_home: "{{ ansible_env.HOME }}/.local/programs/suckless"

  roles:
    - role: auth
      tags:
        - dotfiles-full # for auth
        - install
        - ssh

    - role: update
      tags:
        - install
        - neovim
        - neovim-nightly
        - zsh
        - suckless
        - st
        - dmenu
        - dwm

    - role: base-devel
      tags:
        - install
        - base-devel
        - neovim
        - neovim-nightly
        - suckless
        - st
        - dmenu
        - dwm

    - role: core
      tags:
        - install


  tasks:
  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml

    - name: Check oh-my-zsh is installed
      stat:
        path: ~/.oh-my-zsh/
      register: p
      tags:
        - install
        - zsh

    - import_tasks: tasks/zsh.yml
      when: p.stat.exists == False
      tags:
        - install
        - zsh

    - include_tasks: tasks/dotfiles.yml
      tags:
        - neovim
        - neovim-nightly
        - dotfiles
        - dotfiles-full

    - include_tasks: tasks/neovim.yml
      tags:
        - install
        - neovim
        - neovim-nightly

    - include_tasks: tasks/suckless.yml
      tags:
        - install
        - suckless
        - st
        - dmenu
        - dwm
       
