- hosts: localhost

  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    GH_USER: "aldevv"


  roles:
    - role: update # updates the package manager
      tags:
        - zsh
        - core

    - role: npm # updates the package manager
      tags:
        - dotfiles

    - role: core # updates the package manager
      tags:
        - core

  tasks:
    - import_tasks: tasks/ssh.yml
      tags:
        - dotfiles
        - ssh

    - import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles

    - import_tasks: tasks/zsh.yml
      tags:
        - zsh
