- hosts: localhost

  # tested: debian
  # - neovim / neovim-nightly
  # - copyq

  # to_test:
  # - picom

  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    # dotfiles_repo: "git@github.com:aldevv/dotfiles-chez.git"
    dotfiles_repo_full: "git@github.com:aldevv/.dotfiles.git"
    dotfiles_repo: "https://github.com/aldevv/.dotfiles.git"
    nvim_nightly_home: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}/neovim"
    nvim_home: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}/neovim"
    suckless_home: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}/suckless"
    # this one works but looks worse
    # suckless_home: "{{ lookup('env', 'PROGRAMS', default=ansible_env.HOME ~ '/programs') }}/suckless"

  roles:
    - role: auth
      tags:
        - dotfiles-full 
        - install
        - ssh
        - wiki

    - role: update
      tags:
        - install
        - dotfiles-full 
        - neovim
        - neovim-nightly
        - zsh
        - suckless
        - st
        - dmenu
        - dwm
        - xmonad
        - copyq

    - role: base-devel
      tags:
        - install
        - neovim
        - neovim-nightly
        - core
        - zsh
        - suckless
        - st
        - dmenu
        - dwm
        - xmonad
        - copyq

    - role: core
      tags:
        - install
        - core


  tasks:
  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml

    
    - include_tasks: tasks/dotfiles.yml
      tags:
        - neovim
        - neovim-nightly
        - dotfiles
        - dotfiles-full

    - name: Install zsh
      include_tasks: tasks/zsh.yml
      tags:
        - core
        - install
        - zsh
        - zsh-plugins

    - include_tasks: tasks/neovim.yml
      tags:
        - install
        - neovim
        - neovim-nightly
        - core

    - include_tasks: tasks/suckless.yml
      tags:
        - install
        - suckless
        - st
        - dmenu
        - dwm
        - core
       
    - include_tasks: tasks/xmonad.yml
      tags:
        - install
        - xmonad
       
    - include_tasks: tasks/copyq.yml
      tags:
        - install
        - copyq
       
    - include_tasks: tasks/wiki.yml
      tags:
        - install
        - wiki
