- hosts: localhost
  vars:
    user: "{{ lookup('pipe', 'whoami') }}"
    dotfiles_repo_full: "git@github.com:aldevv/.dotfiles.git"
    dotfiles_repo: "https://github.com/aldevv/.dotfiles.git"
    programs: "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}"
    work: "{{ lookup('env', 'WORK') or ansible_env.HOME ~ '/work' }}"
    projects: "{{ lookup('env', 'PROJECTS') or ansible_env.HOME ~ '/projects' }}"
    learn: "{{ lookup('env', 'LEARN') or ansible_env.HOME ~ '/learn' }}"
    playground: "{{ lookup('env', 'PLAYGROUND') or ansible_env.HOME ~ '/playground' }}"
    code: "{{ lookup('env', 'CODE') or ansible_env.HOME ~ '/playground/code' }}"
    suckless_home: "{{ programs }}/suckless"

  roles:
    - role: auth
      tags:
        - install
        - ssh
        - auth

    - role: update
      tags:
        - update

    - role: base-devel
      tags:
        - install
        - base-devel

    - role: core
      tags:
        - install
        - core

    - role: nix
      tags:
        - install
        - nix

  # check https://github.com/WaylonWalker/devtainer/blob/main/ansible/local.yml
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/install/zsh.yml
    - include: tasks/build/neovim.yml
    - include: tasks/build/suckless.yml
    - include: tasks/wiki.yml
    - include: tasks/folders.yml
    - include: tasks/sudoers.yml
    - include: tasks/hardware.yml
    - include: tasks/build/dunst.yml
    - include: tasks/install/fnm.yml
    - include: tasks/install/slack.yml
