#!/bin/bash
ansible_folder="$HOME/.local/share/ansible/"
if [ -n "$1" ]; then
    docker run -it -v "$ansible_folder:/home/kanon/ansible" --rm arch ansible-playbook -t $1 -K  local.yml
else
    docker run -it -v "$ansible_folder:/home/kanon/ansible" --rm arch bash
fi
