- name: Install fnm dependencies 
  block:
    - include_role:
        name: update
  tags:
    - install
    - core
    - fnm

- name: current shell
  shell: |
    if command -v zsh >/dev/null 2>/dev/null; then
      echo "zsh"
    else 
      echo "bash"
    fi
  register: shell_register
  tags:
    - install
    - core
    - fnm

- name: Install fnm
  shell: |
    curl -fsSL https://fnm.vercel.app/install | {{shell_register.stdout}} -s -- --skip-shell
  args:
    executable: "{{shell_register.stdout}}"
  tags:
    - install
    - fnm

- name: Install fnm for root
  become: true
  shell: |
    sudo curl -fsSL https://fnm.vercel.app/install | sudo {{shell_register.stdout}} -s -- --install-dir "/usr/share"
  args:
    executable: "{{shell_register.stdout}}"
  tags:
    - install
    - fnm

