- name: Install fnm dependencies 
  block:
    - include_role:
        name: update
  tags:
    - install
    - core
    - fnm

- name: Install fnm
  become: yes
  apt:
    name: unzip
  tags:
    - install
    - fnm


- name: Install fnm
  shell: |
    export SHELL=$(which zsh)
    curl -fsSL https://fnm.vercel.app/install | zsh -s -- --skip-shell
  args:
    executable: /bin/bash
  tags:
    - install
    - fnm

