- name: Install fnm dependencies 
  block:
    - include_role:
        name: update
  tags:
    - install
    - core
    - fnm

- name: Install fnm
  shell: |
    curl -fsSL https://fnm.vercel.app/install | zsh
  args:
    executable: /bin/zsh
  tags:
    - install
    - fnm

