- name: install zsh dependencies
  block:
  - include_role:
      name: update
  # - include_role:
  #     name: base-devel
  tags:
    - install
    - core
    - zsh
    - zsh-plugins

- name: Check oh-my-zsh is installed
  stat:
    path: ~/.oh-my-zsh/
  register: var_zsh
  tags:
    - install
    - core
    - zsh

- name: Install zsh
  when: var_zsh.stat.exists == False
  block:
    - name: Create history file
      shell: mkdir -p ~/.cache/zsh/ && touch ~/.cache/zsh/.zsh_history

    - name: Install xsel
      become: true
      package:
        name: xsel

    - name: Install zsh
      become: true
      package: name=zsh

    - name: Install oh-my-zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

    # for user is not possible
    - name: Make zsh the default shell for root
      become: true
      shell: chsh -s $(which zsh)


    
  tags:
    - install
    - core
    - zsh

- name: Install Plugins
  block:
    - name: give autossuggestions to zsh
      git:
         repo: "https://github.com/zsh-users/zsh-autosuggestions"
         dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: give highlightings to zsh
      git:
         repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
         dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

    - name: fzf plugin for zsh
      git:
         repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
         dest: "~/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
         depth: 1

    - name: Check If stowed config
      stat:
        path: ~/.zshrc
      register: var_zsh

    - name: update our zshrc
      when: var_zsh.stat.exists == True
      shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting/' ~/.zshrc
  tags:
    - install
    - zsh
    - zsh-plugins

- name: Check If Custom Theme Available
  stat:
    path: ~/.config/zsh/themes
  register: var_zsh
  tags:
    - install
    - core
    - zsh

- name: Install Custom Theme If Possible
  when: var_zsh.stat.exists == True
  file:
    src: "{{ item }}"
    dest: "~/.oh-my-zsh/custom/themes/{{ item | basename }}"
    state: hard
    force: true
  with_fileglob: '{{ home }}/.config/zsh/themes/*'
  tags:
    - install
    - core
    - zsh
