- name: Install dotfiles
  block:
  - include_role:
      name: auth

  - name: Install Dependencies
    become: true
    apt:
      name:
        - stow
        - wget # for gitsecret
        - gettext

  - name: Download repo normal
    git:
       repo: "{{url}}"
       dest: "{{dotfiles}}"
       recursive: true
       accept_hostkey: true

  - name: Make scripts executable
    file:
      path: "{{dotfiles}}/{{ item }}"
      mode: '0777'
    loop:
      - "linux"
      - "install"

  - name: Stow with linux script
    shell: ./linux
    args:
      chdir: "{{dotfiles}}"

  - name: Run shortcuts script
    shell: bash ./scripts/.local/share/scripts/automation/shortcuts
    args:
      chdir: "{{dotfiles}}"

  - import_tasks: tasks/build/gitsecret.yml 


  vars:
    dotfiles: "{{home}}/.dotfiles"
    url: "git@github.com:aldevv/.dotfiles.git"
  tags: 
    - install
    - dotfiles

