- name: Install dotfile dependencies
  block:
  - include_role:
      name: update
  - include_role:
      name: auth
  tags: 
    - install
    - dotfiles-full

- name: Define dotfiles directory variable
  shell: echo "https://github.com/aldevv/.dotfiles.git"
  register: dotfiles_repo
  tags:
    - neovim
    - neovim-nightly
    - dotfiles

- name: Define dotfiles directory variable
  shell: echo "git@github.com:aldevv/.dotfiles.git"
  register: dotfiles_repo_full
  tags:
    - dotfiles-full
    - install


- name: Install Dotfiles Dependencies
  become: true
  package:
    name:
      - stow
      - git
      - gawk
  tags:
    - install
    - neovim
    - neovim-nightly
    - dotfiles
    - dotfiles-full
  when: "ansible_facts['os_family'] != 'RedHat'"


- name: Install Git-Secret
  when: "ansible_facts['os_family'] != 'Archlinux'"
  block:

    - name: Create directory variable
      shell: echo "{{ lookup('env', 'PROGRAMS') or ansible_env.HOME ~ '/programs' }}"
      register: gitsecret_home

    - name: Clone Git-Secret
      git:
        repo: "https://github.com/sobolevn/git-secret.git"
        dest: "{{ gitsecret_home.stdout }}/git-secret"

    - name: Build Git-Secret
      make:
        chdir: "{{ gitsecret_home.stdout }}/git-secret"
        target: build

    - name: Install Git-Secret
      become: true
      make:
        chdir: "{{ gitsecret_home.stdout }}/git-secret"
        target: install
        params: PREFIX="/usr/local"
  tags:
    - install
    - dotfiles
    - dotfiles-full

- name: Check repo is cloned
  stat:
    path: ~/.dotfiles/
  register: r
  tags:
    - install
    - neovim
    - neovim-nightly
    - dotfiles
    - dotfiles-full




- name: Download repo
  git:
     repo: "{{ dotfiles_repo.stdout }}"
     dest: "~/.dotfiles"
     recursive: no
  tags:
    - neovim
    - neovim-nightly
    - dotfiles
  when: r.stat.exists == False

- name: Download repo full
  git:
     repo: "{{ dotfiles_repo_full.stdout }}"
     dest: "~/.dotfiles"
     recursive: true
     accept_hostkey: true
  tags:
    - install
    - dotfiles-full
  when: r.stat.exists == False

- name: make scripts executable
  file:
    path: "~/.dotfiles/{{ item }}"
    mode: '0777'
  loop:
    - "linux"
    - "install"
  tags:
    - install
    - dotfiles
    - dotfiles-full

- name: Stow folders
  shell: ./linux
  args:
    chdir: ~/.dotfiles/
  tags:
    - dotfiles
    - dotfiles-full
    - install

