
  - name: Install Dependencies
    become: yes
    package:
      name:
        - stow
        - git
        - gpg
    tags:
      - dotfiles
      - dotfiles-full

  - name: Clone Git-Secret
    git:
      repo: "https://github.com/sobolevn/git-secret.git"
      dest: "~/.local/build/git-secret"
    tags:
      - dotfiles
      - dotfiles-full

  - name: Build Git-Secret
    make:
      chdir: "~/.local/build/git-secret"
      target: build
    tags:
      - dotfiles
      - dotfiles-full

  - name: Install Git-Secret
    become: yes
    make:
      chdir: "/home/{{ user }}/.local/build/git-secret"
      target: install
      params: PREFIX="/usr/local"
    tags:
      - dotfiles
      - dotfiles-full

  - name: Download repo
    git:
       repo: "{{ dotfiles_repo }}"
       dest: "~/.dotfiles"
       recursive: no
    tags:
      - dotfiles

  - name: Download repo full
    git:
       repo: "{{ dotfiles_repo_full }}"
       dest: "~/.dotfiles"
       recursive: yes
       accept_hostkey: yes

    tags:
      - dotfiles-full

  # - name: remove this step
  #   shell: cp -r ~/ansible/.dotfiles ~/.dotfiles
  #   tags:
  #     - dotfiles
  #     - dotfiles-full
  #
  - name: make the linux script executable
    file:
      path: ~/.dotfiles/linux
      mode: '0777'
    tags:
      - dotfiles
      - dotfiles-full

  - name: make the install script executable
    file:
      path: ~/.dotfiles/install
      mode: '0777'
    tags:
      - dotfiles
      - dotfiles-full

  - name: Stow folders
    shell: ~/.dotfiles/linux
    tags:
      - dotfiles
      - dotfiles-full
