- name: Install dotfiles
  block:

  - name: Install dotfiles Dependencies
    become: true
    apt:
      name:
        - stow
        - wget # for gitsecret
        - gettext

  - name: Download repo safe
    git:
       repo: "{{url}}"
       dest: "{{dotfiles}}"
       recursive: false

  - name: Make scripts executable
    file:
      path: "{{dotfiles}}/{{ item }}"
      mode: '0777'
    loop:
      - "linux"
      - "install"

  - name: Stow with linux script
    shell: ./linux
    args:
      chdir: "{{dotfiles}}"

  vars:
    dotfiles: "{{home}}/.dotfiles"
    url: "https://github.com/aldevv/.dotfiles"
  tags: 
    - install
    - dotfiles-safe
