  - name: Install chezmoi
    become: yes
    shell: sh -c "$(curl -fsLS chezmoi.io/get) -b /bin"
    # if the repo is named dotfiles then is ok with just this line
    # shell: sh -c "$(curl -fsLS chezmoi.io/get) -b /bin" -- init --apply {{ GH_USER }}

  - name: init dotfiles
    shell: chezmoi init git@github.com:{{ GH_USER }}/dotfiles-chez.git

  - name: apply dotfiles
    shell: chezmoi apply
