  - name: Install Dotfiles Dependencies
    become: true
    package:
      name:
        - stow
        - git
        - gpg
    tags:
      - install
      - neovim
      - neovim-nightly
      - dotfiles
      - dotfiles-full
    when: "ansible_facts['os_family'] != 'RedHat'"

  - name: Clone Git-Secret
    git:
      repo: "https://github.com/sobolevn/git-secret.git"
      dest: "~/.local/build/git-secret"
    tags:
      - install
      - dotfiles
      - dotfiles-full

  - name: Build Git-Secret
    make:
      chdir: "~/.local/build/git-secret"
      target: build
    tags:
      - install
      - dotfiles
      - dotfiles-full

  - name: Install Git-Secret
    become: true
    make:
      chdir: "/home/{{ user }}/.local/build/git-secret"
      target: install
      params: PREFIX="/usr/local"
    tags:
      - dotfiles
      - dotfiles-full
      - install
  - name: Check repo is cloned
    stat:
      path: ~/.dotfiles/
    register: r
    tags:
      - install
      - neovim
      - neovim-nightly
      - dotfiles
      - dotfiles-full


  - name: Download repo
    git:
       repo: "{{ dotfiles_repo }}"
       dest: "~/.dotfiles"
       recursive: no
    tags:
      - neovim
      - neovim-nightly
      - dotfiles
    when: r.stat.exists == False

  - name: Download repo full
    git:
       repo: "{{ dotfiles_repo_full }}"
       dest: "~/.dotfiles"
       recursive: true
       accept_hostkey: true
    tags:
      - dotfiles-full
      - install
    when: r.stat.exists == False

  # - name: remove this step
  #   shell: cp -r ~/ansible/.dotfiles ~/.dotfiles
  #   tags:
  #     - dotfiles
  #     - dotfiles-full
  #
  - name: make the linux script executable
    file:
      path: ~/.dotfiles/linux
      mode: '0777'
    tags:
      - dotfiles
      - dotfiles-full
      - install

  - name: make the install script executable
    file:
      path: ~/.dotfiles/install
      mode: '0777'
    tags:
      - dotfiles
      - dotfiles-full
      - install

  - name: Stow folders
    shell: ~/.dotfiles/linux
    tags:
      - dotfiles
      - dotfiles-full
      - install

  # - name: Delete old .zsh config files (the default ones)
  #   shell: rm ~/.zshrc ~/.zprofile ~/.zshenv
