
  - name: get bitwarden
    import_role:
      name: bitwarden
    tags:
      - dotfiles-full

  - name: Chezmoi Install
    become: yes
    shell: sh -c "$(curl -fsLS chezmoi.io/get) -b /bin"
    tags:
      - dotfiles
      - dotfiles-full

  - name: Chezmoi Init
    # no need to confirm with a "yes"
    shell: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" chezmoi init {{ dotfiles_repo }}
    tags:
      - dotfiles
      - dotfiles-full

  - name: Chezmoi Apply
    shell: chezmoi apply
    tags:
      - dotfiles
      - dotfiles-full
