  - name: Install Dotfiles Dependencies
    become: true
    package:
      name:
        - stow
        - git
    tags:
      - install
      - neovim
      - neovim-nightly
      - dotfiles
      - dotfiles-full
    when: "ansible_facts['os_family'] != 'RedHat'"

  - name: Install Git-Secret
    when: "ansible_facts['os_family'] != 'Archlinux'"
    block:
      - name: Clone Git-Secret
        git:
          repo: "https://github.com/sobolevn/git-secret.git"
          dest: "~/.local/build/git-secret"

      - name: Build Git-Secret
        make:
          chdir: "~/.local/build/git-secret"
          target: build

      - name: Install Git-Secret
        become: true
        make:
          chdir: "/home/{{ user }}/.local/build/git-secret"
          target: install
          params: PREFIX="/usr/local"
    tags:
      - dotfiles
      - dotfiles-full
      - install

  - name: Check repo is cloned
    stat:
      path: ~/.dotfiles/
    register: r
    tags:
      - install
      - neovim
      - neovim-nightly
      - dotfiles
      - dotfiles-full


  - name: Download repo
    git:
       repo: "{{ dotfiles_repo }}"
       dest: "~/.dotfiles"
       recursive: no
    tags:
      - neovim
      - neovim-nightly
      - dotfiles
    when: r.stat.exists == False

  - name: Download repo full
    git:
       repo: "{{ dotfiles_repo_full }}"
       dest: "~/.dotfiles"
       recursive: true
       accept_hostkey: true
    tags:
      - dotfiles-full
      - install
    when: r.stat.exists == False

  - name: make scripts executable
    file:
      path: "~/.dotfiles/{{ item }}"
      mode: '0777'
    loop:
      - "linux"
      - "install"
    tags:
      - dotfiles
      - dotfiles-full
      - install

  - name: Stow folders
    shell: ./linux
    args:
      chdir: ~/.dotfiles/
    tags:
      - dotfiles
      - dotfiles-full
      - install

