- name: Install dotfiles
  block:
  - include_role:
      name: base-devel
  - include_role:
      name: auth

  - include_tasks: tasks/build/gitsecret.yml 
    args:
      apply:
        tags:
          - gitsecret

  - name: Download repo
    git:
       repo: "{{url}}"
       dest: "{{dotfiles}}"
       recursive: true
       accept_hostkey: true

  - name: Make scripts executable
    file:
      path: "{{dotfiles}}/{{ item }}"
      mode: '0777'
    loop:
      - "linux_work"
      - "install"

  - name: Stow with linux_work script
    shell: ./linux_work
    args:
      chdir: "{{dotfiles}}"

  vars:
    dotfiles: "{{home}}/.dotfiles"
    url: "git@github.com:aldevv/.dotfiles.git"
  tags: 
    - install
    - dotfiles-work
