- name: Install dotfiles
  block:

    # check if dotfiles directory exists
  - name: Check if dotfiles directory exists
    stat:
      path: "{{home}}/.dotfiles"
    register: dotfiles_dir

  - name: Download repo
    when: dotfiles_dir.stat.exists == False
    shell: git clone {{url}} {{dotfiles}}

  - name: Make scripts executable
    file:
      path: "{{dotfiles}}/{{ item }}"
      mode: '0777'
    loop:
      - "linux_work"
      - "install"

  - name: Install stow
    become: yes
    package:
      name: stow
      state: present

  - name: Stow with linux_work script
    shell: ./linux_work
    args:
      chdir: "{{dotfiles}}"

  vars:
    dotfiles: "{{home}}/.dotfiles"
    url: "https://github.com/aldevv/.dotfiles"
  tags: 
    - install
    - dotfiles-work
