- name: Install dotfiles
  block:
  - include_role:
      name: base-devel

  - include_tasks: tasks/build/gitsecret.yml 
    args:
      apply:
        tags:
          - gitsecret

  - name: Download repo
    git:
       repo: "{{url}}"
       dest: "{{dotfiles}}"
       recursive: false

  - name: Make scripts executable
    file:
      path: "{{dotfiles}}/{{ item }}"
      mode: '0777'
    loop:
      - "linux"
      - "install"

  - name: Stow with linux script
    shell: ./linux
    args:
      chdir: "{{dotfiles}}"

  vars:
    dotfiles: "{{home}}/.dotfiles"
    url: "https://github.com/aldevv/.dotfiles"
  tags: 
    - install
    - dotfiles
