- name: Start Dotfiles setup
  block:
  - name: Install auth for dotfiles
    block:
      - include_role:
          name: auth
    tags:
      - install
      - dotfiles
      - build

  - name: Install dependencies for dotfiles
    block: 
      - name: Install dotfiles Dependencies
        become: true
        apt:
          name:
            - stow
            - wget  # for gitsecret
            - gettext
    tags:
      - install
      - dotfiles

  - name: Clone dotfiles recursive
    block:
      - name: Download repo normal
        git:
          repo: "{{ url }}"
          dest: "{{ dotfiles }}"
          recursive: true
          accept_hostkey: true
    tags:
      - install
      - dotfiles
      - build

  - name: check if dotfiles exist
    stat:
      path: "{{ dotfiles }}"
    register: dot_stat

  # do this one if dotfiles don't exist
  - name: Clone dotfiles 
    when: not dot_stat.stat.exists
    block:
      - name: Download repo normal
        git:
          repo: "{{ url_http }}"
          dest: "{{ dotfiles }}"
          recursive: false
    tags:
      - install
      - dotfiles

  - name: Setup the cloned dotfiles
    block:
      - name: Make scripts executable
        file:
          path: "{{ dotfiles }}/{{ item }}"
          mode: '0777'
        loop:
          - "linux"
          - "install"

      - name: Stow with linux script
        shell: ./linux
        args:
          chdir: "{{ dotfiles }}"

      - name: Run shortcuts script
        shell: bash ./scripts/.local/share/scripts/automation/shortcuts
        args:
          chdir: "{{ dotfiles }}"
    tags:
      - install
      - dotfiles


  - name: setup git secret
    block:
      - import_tasks: tasks/build/gitsecret.yml 
    tags:
      - install
      - dotfiles
      - build

  vars:
    dotfiles: "{{ home }}/.dotfiles"
    url: "git@github.com:aldevv/.dotfiles.git"
    url_http: "https://github.com/aldevv/.dotfiles"

  tags: 
    - install
    - dotfiles

