- name: Create home folders
  shell: |
    [[ ! -d {{ work }} ]] && mkdir {{ work }}
    [[ ! -d {{ projects }} ]] && mkdir {{ projects }}
    [[ ! -d {{ learn }} ]] && mkdir {{ learn }}
    [[ ! -d {{ code }} ]] && mkdir {{ code }}
    [[ ! -d {{ programs }} ]] && mkdir {{ programs }}
    [[ ! -d {{ builds }} ]] && mkdir {{ builds }}
  args:
    executable: /bin/bash
  tags:
    - install
    - folders
