- name: Create my folders
  shell: |
    [ ! -d {{home}}/.local/bin ] && mkdir -p {{ home }}/.local/bin
    [ ! -d {{ work }} ] && mkdir -p {{ work }}
    [ ! -d {{ projects }} ] && mkdir -p {{ projects }}
    [ ! -d {{ learn }} ] && mkdir -p {{ learn }}
    [ ! -d {{ code }} ] && mkdir -p {{ code }}
    [ ! -d {{ programs }} ] && mkdir -p {{ programs }}
    [ ! -d {{ builds }} ] && mkdir -p {{ builds }}
  args:
    executable: /bin/sh
  no_log: True
  ignore_errors: true
  tags:
    - always
