- name: enable xbacklight
  become: yes
  shell: |
    if [[ ! -e /sys/class/backlight/intel_backlight ]]; then
      exit 1
    fi

    cat > /etc/X11/xorg.conf << EOF
        Section "Device"
            Identifier  "Intel Graphics" 
            Driver      "intel"
            Option      "Backlight"  "intel_backlight"
        EndSection
    EOF
  args:
    executable: /bin/bash
  tags:
    - install
    - hardware

