- name: Stow nvim dotfile
  shell: stow nvim && cd -
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles"
  tags:
    - core
    - neovim

- name: Create bujo folder
  shell: mkdir -p ~/.cache/bujo
  tags:
    - install
    - core
    - neovim

# current version in ubuntu is 0,4,4 which doesn't have lua
# - name: Install Neovim
#   become: yes
#   package:
#     name: neovim
#   tags:
#     - nvim
#     - core
#     - install


- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ nvim_home }}"
    depth: 1
  tags:
    - install
    - core
    - neovim

- name: Build neovim
  become: yes
  shell: "make clean && make -j 20"
  args:
    chdir: "{{ nvim_home }}"
  tags:
    - install
    - core
    - neovim

- name: Install neovim
  become: yes
  shell: "make install"
  args:
    chdir: "{{ nvim_home }}"
  tags:
    - install
    - core
    - neovim

- name: Download Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
  tags:
    - install
    - core
    - neovim


- name: Run PackerInstall
  shell: nvim --headless -c 'PackerInstall'
  tags:
    - install
    - core
    - neovim

- name: Run PackerSync
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags:
    - install
    - core
    - neovim



