- name: Clone suckless programs
  block:
    - name: Create programs folder
      shell: "mkdir -p {{ suckless_home }}"

    - name: Clone suckless programs
      git:
        repo: 'https://github.com/aldevv/suckless.git'
        dest: "{{ suckless_home }}"
        depth: 1
  tags:
    - suckless
    - st
    - dmenu
    - install

- name: Build all suckless programs
  become: true
  shell: "make clean && make && make install"
  args:
    chdir: "{{ suckless_home }}/{{ item }}"
  loop:
    - "st"
    - "dmenu"
  tags:
    - suckless
    - install
    - st
    - dmenu

- name: Build st 
  become: true
  shell: "make clean && make && make install"
  args:
    chdir: "{{ suckless_home }}/st"
  tags:
    - install
    - suckless
    - st

- name: Build dmenu 
  become: true
  shell: "make clean && make && make install"
  args:
    chdir: "{{ suckless_home }}/dmenu"
  tags:
    - install
    - suckless
    - dmenu

