- name: get current user
  shell: whoami
  register: user
  tags:
    install
    sudoers


- name: add user to sudoers
  become: yes
  shell: |
    echo -e '{{ user.stdout }}\tALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
  args:
    executable: /bin/bash
  tags:
    install
    sudoers
