- include_role:
    name: auth
  tags:
    - install
    - wiki

- name: Clone wiki
  git:
    repo: git@github.com:aldevv/wiki.git
    dest: ~/.local/share/wiki
    depth: 1
    accept_hostkey: true
  tags:
    - install
    - wiki
