- name: Check oh-my-zsh is installed
  stat:
    path: ~/.oh-my-zsh/
  register: p
  tags:
    - install
    - core
    - zsh

- name: Install zsh
  when: p.stat.exists == False
  block:
    - name: Install xsel
      become: true
      package:
        name: xsel

    - name: Install zsh
      become: true
      apt: name=zsh

    - name: Make zsh the default shell
      become: true
      shell: chsh -s $(which zsh)

    - name: Install oh-my-zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

    - name: give autossuggestions to zsh
      git:
         repo: "https://github.com/zsh-users/zsh-autosuggestions"
         dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

    - name: give highlightings to zsh
      git:
         repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
         dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"

    - name: update our zshrc
      shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting/' ~/.zshrc
  tags:
    - install
    - core
    - zsh

