- name: Install pynvim
  command: "pip install --break-system-packages {{ item }}"
  with_items: 
      - pynvim
      - ranger-fm
      # - ueberzug no longer maintained
      - yq
      - jc
      - jq
      - brotab
