- name: Install pip packages
  become: yes
  command: pip install --break-system-packages {{item}}
  with_items:
    - github3.py
    - urllib3

    - pynvim
    - ranger-fm
    # - ueberzug no longer maintained
    - yq
    - jc
    - jq
    # - brotab
