  - name: Install core programs
    become: true
    tags:
      - core
    pacman:
      name:
        - "noto-fonts-emoji"
        - "base-devel"
        - "cmake"
        - "flatpak"
        - "npm"
        - "rclone"
        - "autorandr"
        - "picom"
        - "sxhkd"
        - "dunst"
        - "sxiv"
        - "pavucontrol"
        - "firefox"
        - "zathura"
        - "zathura-pdf-mupdf"
        - "xsel"
        - "xclip"
        - "fcitx"
        - "fcitx-qt5"
        - "fcitx-configtool"
        - "fcitx-mozc"
        - "tldr"
        - "python-pipenv"
        - "pass"
        - "tmux"
        - ripgrep
        - ripgrep-all
        - chromium
        - exa
        - fd
        - unzip
        - bitwarden
        - bitwarden-cli
        - jq
        - chafa

  - name: Install misc programs
    become: true
    pacman:
      name:
        - docker
        - docker-compose
        - ctags
        - rust
        - github-cli
        - rsync
        - alacritty
        - shellcheck
        - flameshot

  - name: Install package from AUR using a Pacman compatible AUR helper
    shell: "[ -x $(command -v ngrok) ] && yay --noconfirm -S {{ item }}"
    loop:
        - xidlehook
        - ngrok
        - gitflow-avh
        - stylua
        - selene-linter
        - notion-app-enhanced
        - neovide-git
        - pacolog
        - insomnia-bin
        - downgrade
        - clipcat
        - git-secret

  - name: Install programs for development
    become: true
    pacman:
      name:
        - shfmt

  - name: Install qmk programs for custom keyboard
    become: true
    shell: "[ -x $(command -v avrdude) ] && yay --noconfirm -S {{ item }}"
    loop:
      - "avr-libc"
      - "avr-gcc"
      - "avrdude"

