  - name: Install core programs
    become: yes
    become_user: root
    apt:
      name:
        - "noto-fonts-emoji"
        - "base-devel"
        - "cmake"
        - "flatpak"
        - "npm"
        - "rclone"
        - "autorandr"
        - "picom"
        - "sxhkd"
        - "dunst"
        - "sxiv"
        - "pavucontrol"
        - "firefox"
        - "zathura"
        - "zathura-pdf-mupdf"
        - "xsel"
        - "xclip"
        - "fcitx"
        - "fcitx-qt5"
        - "fcitx-configtool"
        - "fcitx-mozc"
        - "fzf"
        - "tldr"
        - "shfmt"
        - "python-pipenv"
        - "pass"
        - "tmux"
        - ripgrep
        - ripgrep-all
        - chromium
        - exa
        - fd
        - unzip

  - name: Install misc programs
    become: yes
    become_user: root
    apt:
      name:
        - docker
        - docker-compose
        - ctags
        - rust
        - github-cli
        - rsync
        - alacritty
        - shellcheck
        - flameshot

  - name: Install qmk programs for custom keyboard
    become: yes
    become_user: root
    apt:
      name:
        - "avr-libc"
        - "avr-gcc"
        - "avrdude"
