- name: Install core programs
  become: yes
  apt:
    name:
      - "fonts-noto-color-emoji"
      - "build-essential"
      - "cmake"
      - "flatpak"
      - "npm"
      - "rclone"
      - "autorandr"
      - "picom"
      - "sxhkd"
      - "dunst"
      - "sxiv"
      - "pavucontrol"
      - "firefox"
      - "zathura"
      - "zathura-pdf-poppler"
      - "xsel"
      - "xclip"
      - "fcitx"
      - "fcitx-frontend-qt5"
      - "kde-config-fcitx"
      - "fcitx-mozc"
      - "fzf"
      - "tldr"
      - "pipenv"
      - "pass"
      - "tmux"
      - "chromium-browser"
      - "unzip"
      - "flameshot"
      - "ripgrep"
      - "fd-find"
      - "exa"
      - "alacritty"


- name: Install misc programs
  become: yes
  apt:
    name:
      - gh
      - docker.io
      - docker-compose
      - exuberant-ctags
      - rsync
      - shellcheck


- import_tasks: ./custom/rust.yml
  tags:
    - install
    - rust


- name: Install development programs
  become: yes
  apt:
    name:
        - firefox
  tags:
    - core
    - develop


- name: Install qmk programs for custom keyboard
  become: yes
  apt:
    name:
      - "avr-libc"
      - "gcc-avr"
      - "avrdude"
