- name: add keyboard config
  become: true
  shell: |
      cat > /etc/X11/xorg.conf.d/00-keyboard.conf << EOF
      Section "InputClass"
              Identifier      "system-keyboard"
              MatchIsKeyboard     "on"
              Option          "XkbLayout" "latam"
              Option          "XkbVariant" "colemak"
              Option          "XkbOptions" "caps:escape"
      EndSection
      EOF
  tags:
    - install
    - keyboard
