- name: Install ssh
  block:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ dest_key | dirname }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0700

    - name: Install ssh key
      copy:
        content: "{{ id_rsa }}"
        dest: "{{ dest_key }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

    - name: Install pub ssh key
      copy:
        content: "{{ id_rsa_pub }}"
        dest: "{{ dest_pub_key }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{home}}/.ssh/*.pub"

- name: Install gnupg
  block:
    - name: Ensure .gnupg directory exists.
      file:
        dest: "{{ dest_key_gpg_folder | dirname }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0700

    - name: Create gpg key
      copy:
        content: "{{ gnu_pub }}"
        dest: "{{home}}/public.key"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Create gpg key
      copy:
        content: "{{ gnu_priv }}"
        dest: "{{home}}/private.key"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Install gpg key
      shell: |
         gpg --import ~/private.key
         gpg --import ~/public.key

    - name: Remove private
      file:
        path: "{{item}}"
        state: absent
      loop: 
        - "{{home}}/private.key"
        - "{{home}}/public.key"

