- name: install docker
  block:
  - name: Add docker to apt repository
    become: true
    shell: |
      if [[ -f /etc/apt/keyrings/docker.asc ]]; then
        return 0
      fi

      apt update
      apt install ca-certificates curl
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt update

  - name: Install docker using apt
    become: true
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin

  - name: Add permissions
    become: true
    shell: | 
      if grep -q docker <<< "$(groups {{ user }})"; then
        return 0
      fi

      groupadd docker
      usermod -aG docker {{ user }}
    args:
      executable: /bin/bash

  tags:
    - install
    - docker

