#!/bin/bash
export CARGO_BUILD_HOME=aarch64-linux-android
export ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp
export ANSIBLE_REMOTE_TEMP=$HOME/.ansible/tmp
# missing ansible variables
pkg install git tsu neovim rust python3 \
    fzf fd ripgrep rust-analyzer rust-docs \
    rustc-dev rustc-nightly rust-src-nightly \
    gettext
# gettext contains envsubst binary, needed for shortcut scripts
pip install wheel ansible


