  - name: Install Basic Dependencies
    become: yes
    pacman:
      name:
        - base-devel
        - cmake
        - pkg-config
        - unzip
        - ninja
        - tree-sitter
        - curl
