  - name: Install Basic Development Dependencies
    become: true
    apt:
      name:
        - git
        - build-essential
        - cmake
        - pkg-config
        - automake
        - libtool
        - unzip
        - ninja-build
        - gettext
        - libtool
        - libtool-bin
        - autoconf
        - g++
        - curl
        - doxygen
        - npm
        - python3-venv
        - python3-pip


  
